//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIITS.DTLMS.BL.DtmmsWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DtmmsWebService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveIndentDetails", ReplyAction="http://tempuri.org/IService1/SaveIndentDetailsResponse")]
        bool SaveIndentDetails(System.Data.DataTable dtIndentDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInvoiceDetails", ReplyAction="http://tempuri.org/IService1/SaveInvoiceDetailsResponse")]
        string[] SaveInvoiceDetails(System.Data.DataTable dtInvoiceDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SavePseudoIndentDetails", ReplyAction="http://tempuri.org/IService1/SavePseudoIndentDetailsResponse")]
        string[] SavePseudoIndentDetails(System.Data.DataTable dtDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveRVData", ReplyAction="http://tempuri.org/IService1/SaveRVDataResponse")]
        bool SaveRVData(System.Data.DataTable dtRVDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertUserDetailsToDTLMS", ReplyAction="http://tempuri.org/IService1/insertUserDetailsToDTLMSResponse")]
        string insertUserDetailsToDTLMS(System.Data.DataTable table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUserDetailsToDTLMS", ReplyAction="http://tempuri.org/IService1/updateUserDetailsToDTLMSResponse")]
        string updateUserDetailsToDTLMS(System.Data.DataTable table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivateDeactivateUser", ReplyAction="http://tempuri.org/IService1/ActivateDeactivateUserResponse")]
        string ActivateDeactivateUser(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/changePassword", ReplyAction="http://tempuri.org/IService1/changePasswordResponse")]
        string changePassword(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTcMaster", ReplyAction="http://tempuri.org/IService1/UpdateTcMasterResponse")]
        string UpdateTcMaster(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnInvoiceAcknowledgement", ReplyAction="http://tempuri.org/IService1/ReturnInvoiceAcknowledgementResponse")]
        string ReturnInvoiceAcknowledgement(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/purchaseOrder", ReplyAction="http://tempuri.org/IService1/purchaseOrderResponse")]
        string purchaseOrder(System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReceiptOfMaterialPO", ReplyAction="http://tempuri.org/IService1/ReceiptOfMaterialPOResponse")]
        string ReceiptOfMaterialPO(System.Data.DataSet ds, int flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDTR_Code", ReplyAction="http://tempuri.org/IService1/GetDTR_CodeResponse")]
        string GetDTR_Code(int Qty, long POIDMMS, long POVenIDMMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveUserDetails", ReplyAction="http://tempuri.org/IService1/SaveUserDetailsResponse")]
        bool SaveUserDetails(System.Data.DataTable dtUserdetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActDeActUser", ReplyAction="http://tempuri.org/IService1/ActDeActUserResponse")]
        bool ActDeActUser(System.Data.DataTable dtUserdetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePWD", ReplyAction="http://tempuri.org/IService1/ChangePWDResponse")]
        bool ChangePWD(System.Data.DataTable dtUserdetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ApproveRejectActionDtlms", ReplyAction="http://tempuri.org/IService1/ApproveRejectActionDtlmsResponse")]
        string ApproveRejectActionDtlms(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateReplaceDetails", ReplyAction="http://tempuri.org/IService1/UpdateReplaceDetailsResponse")]
        string[] UpdateReplaceDetails(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMMSUserdetails", ReplyAction="http://tempuri.org/IService1/GetMMSUserdetailsResponse")]
        System.Data.DataTable GetMMSUserdetails(string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsrDetail", ReplyAction="http://tempuri.org/IService1/GetUsrDetailResponse")]
        System.Data.DataTable GetUsrDetail(string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveTcDetails", ReplyAction="http://tempuri.org/IService1/SaveTcDetailsResponse")]
        bool SaveTcDetails(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveRepairer_invoice", ReplyAction="http://tempuri.org/IService1/saveRepairer_invoiceResponse")]
        string[] saveRepairer_invoice(System.Data.DataTable RepairDetails, System.Data.DataTable dtItem_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveItem_code", ReplyAction="http://tempuri.org/IService1/saveItem_codeResponse")]
        bool saveItem_code(string Item_code, string tc_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerateInvoiceNo", ReplyAction="http://tempuri.org/IService1/GenerateInvoiceNoResponse")]
        string GenerateInvoiceNo(string sOfficeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveNewDtcCommission", ReplyAction="http://tempuri.org/IService1/SaveNewDtcCommissionResponse")]
        string[] SaveNewDtcCommission(System.Data.DataTable dtInvoiceDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_StoreID", ReplyAction="http://tempuri.org/IService1/get_StoreIDResponse")]
        string get_StoreID(string DTLMS_SstoreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RVItem_code", ReplyAction="http://tempuri.org/IService1/RVItem_codeResponse")]
        bool RVItem_code(System.Data.DataTable dtRV_Item_Code, string sPO_NO, string sRvno, string sRvdate, string sOmno, string sOmdate, string sDTrCodes, string sMMSAutoRVNum, string sDeliverChallenNo, string sDeliverDate,string MMS_Auto_Invno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveDtlmsTackDetails", ReplyAction="http://tempuri.org/IService1/SaveDtlmsTackDetailsResponse")]
        bool SaveDtlmsTackDetails(System.Data.DataTable dtDtlmsTrack);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTcMasterStoreRv", ReplyAction="http://tempuri.org/IService1/UpdateTcMasterStoreRvResponse")]
        string UpdateTcMasterStoreRv(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateItemTcMapping", ReplyAction="http://tempuri.org/IService1/UpdateItemTcMappingResponse")]
        string UpdateItemTcMapping(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRepairGatePass", ReplyAction="http://tempuri.org/IService1/UpdateRepairGatePassResponse")]
        void UpdateRepairGatePass(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCrStatus", ReplyAction="http://tempuri.org/IService1/updateCrStatusResponse")]
        bool updateCrStatus(string strQry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastPricingDate", ReplyAction="http://tempuri.org/IService1/GetLastPricingDateResponse")]
        string GetLastPricingDate(string offCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTCDetails", ReplyAction="http://tempuri.org/IService1/GetTCDetailsResponse")]
        System.Data.DataTable GetTCDetails(string sdtrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_ItemQty", ReplyAction="http://tempuri.org/IService1/get_ItemQtyResponse")]
        string[] get_ItemQty(string sItemCode, string sOfficeCode, string sQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRepairerAutoINvoiceNum", ReplyAction="http://tempuri.org/IService1/GetRepairerAutoINvoiceNumResponse")]
        string GetRepairerAutoINvoiceNum(string offCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRepairerAutoRVNum", ReplyAction="http://tempuri.org/IService1/GetRepairerAutoRVNumResponse")]
        string GetRepairerAutoRVNum(string offCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveOil_invoice", ReplyAction="http://tempuri.org/IService1/saveOil_invoiceResponse")]
        string[] saveOil_invoice(System.Data.DataTable OilDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveRVOil_invoice", ReplyAction="http://tempuri.org/IService1/saveRVOil_invoiceResponse")]
        string[] saveRVOil_invoice(System.Data.DataTable OilDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOilAutoInvoiceNum", ReplyAction="http://tempuri.org/IService1/GetOilAutoInvoiceNumResponse")]
        string GetOilAutoInvoiceNum(string offCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOilAutoRVNum", ReplyAction="http://tempuri.org/IService1/GetOilAutoRVNumResponse")]
        string GetOilAutoRVNum(string offCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_TotalItemQty", ReplyAction="http://tempuri.org/IService1/get_TotalItemQtyResponse")]
        string get_TotalItemQty(string sItemCode, string sOfficeCode);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/saveRepairer_Oilinvoice", ReplyAction = "http://tempuri.org/IService1/saveRepairer_OilinvoiceResponse")]
        string[] saveRepairer_Oilinvoice(System.Data.DataTable RepairerOilDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : IIITS.DTLMS.BL.DtmmsWebService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<IIITS.DTLMS.BL.DtmmsWebService.IService1>, IIITS.DTLMS.BL.DtmmsWebService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveIndentDetails(System.Data.DataTable dtIndentDetails) {
            return base.Channel.SaveIndentDetails(dtIndentDetails);
        }
        
        public string[] SaveInvoiceDetails(System.Data.DataTable dtInvoiceDetails) {
            return base.Channel.SaveInvoiceDetails(dtInvoiceDetails);
        }
        
        public string[] SavePseudoIndentDetails(System.Data.DataTable dtDetails) {
            return base.Channel.SavePseudoIndentDetails(dtDetails);
        }
        
        public bool SaveRVData(System.Data.DataTable dtRVDetails) {
            return base.Channel.SaveRVData(dtRVDetails);
        }
        
        public string insertUserDetailsToDTLMS(System.Data.DataTable table) {
            return base.Channel.insertUserDetailsToDTLMS(table);
        }
        
        public string updateUserDetailsToDTLMS(System.Data.DataTable table) {
            return base.Channel.updateUserDetailsToDTLMS(table);
        }
        
        public string ActivateDeactivateUser(System.Data.DataTable dt) {
            return base.Channel.ActivateDeactivateUser(dt);
        }
        
        public string changePassword(System.Data.DataTable dt) {
            return base.Channel.changePassword(dt);
        }
        
        public string UpdateTcMaster(System.Data.DataTable dt) {
            return base.Channel.UpdateTcMaster(dt);
        }
        
        public string ReturnInvoiceAcknowledgement(System.Data.DataTable dt) {
            return base.Channel.ReturnInvoiceAcknowledgement(dt);
        }
        
        public string purchaseOrder(System.Data.DataSet ds) {
            return base.Channel.purchaseOrder(ds);
        }
        
        public string ReceiptOfMaterialPO(System.Data.DataSet ds, int flag) {
            return base.Channel.ReceiptOfMaterialPO(ds, flag);
        }
        
        public string GetDTR_Code(int Qty, long POIDMMS, long POVenIDMMS) {
            return base.Channel.GetDTR_Code(Qty, POIDMMS, POVenIDMMS);
        }
        
        public bool SaveUserDetails(System.Data.DataTable dtUserdetails) {
            return base.Channel.SaveUserDetails(dtUserdetails);
        }
        
        public bool ActDeActUser(System.Data.DataTable dtUserdetails) {
            return base.Channel.ActDeActUser(dtUserdetails);
        }
        
        public bool ChangePWD(System.Data.DataTable dtUserdetails) {
            return base.Channel.ChangePWD(dtUserdetails);
        }
        
        public string ApproveRejectActionDtlms(System.Data.DataTable dt) {
            return base.Channel.ApproveRejectActionDtlms(dt);
        }
        
        public string[] UpdateReplaceDetails(System.Data.DataTable dt) {
            return base.Channel.UpdateReplaceDetails(dt);
        }
        
        public System.Data.DataTable GetMMSUserdetails(string username, string pwd) {
            return base.Channel.GetMMSUserdetails(username, pwd);
        }
        
        public System.Data.DataTable GetUsrDetail(string username, string pwd) {
            return base.Channel.GetUsrDetail(username, pwd);
        }
        
        public bool SaveTcDetails(string query) {
            return base.Channel.SaveTcDetails(query);
        }
        
        public string[] saveRepairer_invoice(System.Data.DataTable RepairDetails, System.Data.DataTable dtItem_code) {
            return base.Channel.saveRepairer_invoice(RepairDetails, dtItem_code);
        }
        
        public bool saveItem_code(string Item_code, string tc_code) {
            return base.Channel.saveItem_code(Item_code, tc_code);
        }
        
        public string GenerateInvoiceNo(string sOfficeCode) {
            return base.Channel.GenerateInvoiceNo(sOfficeCode);
        }
        
        public string[] SaveNewDtcCommission(System.Data.DataTable dtInvoiceDetails) {
            return base.Channel.SaveNewDtcCommission(dtInvoiceDetails);
        }
        
        public string get_StoreID(string DTLMS_SstoreId) {
            return base.Channel.get_StoreID(DTLMS_SstoreId);
        }
        
        public bool RVItem_code(System.Data.DataTable dtRV_Item_Code, string sPO_NO, string sRvno, string sRvdate, string sOmno, string sOmdate, string sDTrCodes, string sMMSAutoRVNum, string sDeliverChallenNo, string sDeliverDate,string MMS_Auto_Invno) {
            return base.Channel.RVItem_code(dtRV_Item_Code, sPO_NO, sRvno, sRvdate, sOmno, sOmdate, sDTrCodes, sMMSAutoRVNum, sDeliverChallenNo, sDeliverDate, MMS_Auto_Invno);
        }
        
        public bool SaveDtlmsTackDetails(System.Data.DataTable dtDtlmsTrack) {
            return base.Channel.SaveDtlmsTackDetails(dtDtlmsTrack);
        }
        
        public string UpdateTcMasterStoreRv(System.Data.DataTable dt) {
            return base.Channel.UpdateTcMasterStoreRv(dt);
        }
        
        public string UpdateItemTcMapping(System.Data.DataTable dt) {
            return base.Channel.UpdateItemTcMapping(dt);
        }
        
        public void UpdateRepairGatePass(System.Data.DataTable dt) {
            base.Channel.UpdateRepairGatePass(dt);
        }
        
        public bool updateCrStatus(string strQry) {
            return base.Channel.updateCrStatus(strQry);
        }
        
        public string GetLastPricingDate(string offCode) {
            return base.Channel.GetLastPricingDate(offCode);
        }
        
        public System.Data.DataTable GetTCDetails(string sdtrCode) {
            return base.Channel.GetTCDetails(sdtrCode);
        }
        
        public string[] get_ItemQty(string sItemCode, string sOfficeCode, string sQty) {
            return base.Channel.get_ItemQty(sItemCode, sOfficeCode, sQty);
        }
        
        public string GetRepairerAutoINvoiceNum(string offCode) {
            return base.Channel.GetRepairerAutoINvoiceNum(offCode);
        }
        
        public string GetRepairerAutoRVNum(string offCode) {
            return base.Channel.GetRepairerAutoRVNum(offCode);
        }
        
        public string[] saveOil_invoice(System.Data.DataTable OilDetails) {
            return base.Channel.saveOil_invoice(OilDetails);
        }
        
        public string[] saveRVOil_invoice(System.Data.DataTable OilDetails) {
            return base.Channel.saveRVOil_invoice(OilDetails);
        }
        
        public string GetOilAutoInvoiceNum(string offCode) {
            return base.Channel.GetOilAutoInvoiceNum(offCode);
        }
        
        public string GetOilAutoRVNum(string offCode) {
            return base.Channel.GetOilAutoRVNum(offCode);
        }
        
        public string get_TotalItemQty(string sItemCode, string sOfficeCode) {
            return base.Channel.get_TotalItemQty(sItemCode, sOfficeCode);
        }
        public string[] saveRepairer_Oilinvoice(System.Data.DataTable RepairerOilDetails)
        {
            return base.Channel.saveRepairer_Oilinvoice(RepairerOilDetails);
        }
    }
}
